# Generated by Django 5.1.4 on 2026-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Base de données'), ('devops', 'DevOps'), ('mobile', 'Mobile'), ('other', 'Autre')], default='backend', max_length=20, verbose_name='Catégorie')),
                ('proficiency', models.IntegerField(help_text='Valeur entre 0 et 100', verbose_name='Niveau (%)')),
                ('icon', models.CharField(blank=True, help_text='Ex: devicon-django-plain, devicon-python-plain', max_length=100, verbose_name='Icône (classe CSS/SVG name)')),
                ('color', models.CharField(default='#3b82f6', help_text='Code HEX, ex: #3b82f6', max_length=7, verbose_name='Couleur accent')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('problem', models.TextField(blank=True, verbose_name='Problème résolu')),
                ('solution', models.TextField(blank=True, verbose_name='Solution apportée')),
                ('impact', models.TextField(blank=True, verbose_name='Impact / Résultats')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('fullstack', 'Fullstack'), ('mobile', 'Mobile'), ('api', 'API / Microservice')], default='fullstack', max_length=20, verbose_name='Catégorie')),
                ('github_url', models.URLField(blank=True, verbose_name='Lien GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='Lien Démo')),
                ('featured', models.BooleanField(default=False, verbose_name='Projet vedette')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('technologies', models.ManyToManyField(blank=True, to='portfolio.skill', verbose_name='Technologies')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
