# Generated by Django 5.1.4 on 2026-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_exp', models.PositiveIntegerField(default=3, verbose_name="Années d'expérience")),
                ('projects_done', models.PositiveIntegerField(default=10, verbose_name='Projets livrés')),
                ('clients', models.PositiveIntegerField(default=8, verbose_name='Clients satisfaits')),
                ('coffee', models.PositiveIntegerField(default=500, verbose_name='Cafés ☕')),
            ],
            options={
                'verbose_name': 'Statistiques À propos',
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Ex : 2022 – 2024', max_length=50, verbose_name='Période')),
                ('title', models.CharField(max_length=120, verbose_name='Titre du poste')),
                ('description', models.CharField(max_length=250, verbose_name='Description courte')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Élément Timeline',
                'verbose_name_plural': 'Éléments Timeline',
                'ordering': ['order'],
            },
        ),
    ]
